apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test-container
    image: nginx
    env:
    - name: MYSETTINGS_JSON
      valueFrom:
        configMapKeyRef:
          name: mysettings-config3
          key: mysettings.json
