apiVersion: v1
kind: Pod
metadata:
  name: mynginx
  labels:
    environment: production
    tier: frontend
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    env:
    - name: MYSETTINGS_NAME
      valueFrom:
        configMapKeyRef:
          name: mysettings-config1
          key: name
    - name: MYSETTINGS_LOCATION
      valueFrom:
        configMapKeyRef:
          name: mysettings-config1
          key: location
