apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myhelloapp-rs
spec:
  replicas: 5
  selector:
    matchExpressions:
    - {key: app, operator: In, values: [nginx-app, demo-app]}
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-app
    spec:
      containers:
      - name: mynginx-con
        image: nginx:1.19.0
        ports:
        - containerPort: 80
        imagePullPolicy: Always